### ISSUE TITLE
Package.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by patrickjtoy** [fcharron/last-cursor-position#16] opened 2015-04-03 17:03 UTC
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `last-cursor-position` package
```
Package.getStylesheetsPath (atom\app-0.189.0\resources\app\src\package.js:448:9)
Package.getStylesheetPaths (atom\app-0.189.0\resources\app\src\package.js:459:32)
```

**Comment by fcharron** [comment] 2015-04-03 17:05
duplicate of #14, already fixed, just need to update atom repo

**Closed** 2015-04-03 17:05 UTC
Labels: duplicate
